<script setup>
import { ref } from 'vue'
const form=ref({nombreCompleto:'',contactoAlternativo:'',edad:'',fechaNacimiento:'',telefonoPersonal:'',telefonoTrabajo:'',emailPersonal:'',emailTrabajo:'',calle:'',colonia:'',municipio:'',estado:'',codigoPostal:'',tallerId:''})
const foto=ref(null),mensaje=ref(''),error=ref(false),cargando=ref(false)
function onFile(e){foto.value=e.target.files?.[0]||null;if(foto.value&&foto.value.size>7*1024*1024){mensaje.value='La foto supera 7 MB.';error.value=true;foto.value=null;e.target.value=''}}
async function guardar(){mensaje.value='';error.value=false;cargando.value=true;try{const data=new FormData();for(const [k,v] of Object.entries(form.value))data.append(k,v);if(foto.value)data.append('foto',foto.value);const sesion=JSON.parse(localStorage.getItem('sesion')||'{}');const r=await fetch('http://localhost:8080/api/clientes',{method:'POST',headers:{Authorization:`Bearer ${sesion.token||''}`},body:data});const body=await r.json();if(!r.ok)throw Error(body.mensaje||'No se pudo guardar.');mensaje.value=body.mensaje;form.value=Object.fromEntries(Object.keys(form.value).map(k=>[k,'']));foto.value=null;document.querySelector('#foto-cliente').value=''}catch(e){mensaje.value=e.message||'Error de conexion.';error.value=true}finally{cargando.value=false}}
const fields=[['nombreCompleto','Nombre completo','text'],['contactoAlternativo','Contacto alternativo','text'],['edad','Edad','number'],['fechaNacimiento','Fecha de nacimiento','date'],['telefonoPersonal','Telefono personal','tel'],['telefonoTrabajo','Telefono de trabajo','tel'],['emailPersonal','Email personal','email'],['emailTrabajo','Email de trabajo (opcional)','email'],['calle','Calle','text'],['colonia','Colonia','text'],['municipio','Municipio','text'],['estado','Estado','text'],['codigoPostal','Codigo postal','text'],['tallerId','ID del taller','number']]
</script>
<template><main class="min-h-screen bg-zinc-100 px-4 py-8 text-zinc-900"><section class="mx-auto max-w-4xl border border-zinc-200 bg-white p-6 shadow-sm sm:p-8"><header class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-zinc-500">Taller mecanico</p><h1 class="mt-1 text-2xl font-semibold">Registro de cliente</h1></div><RouterLink to="/clientes" class="text-sm underline">Ver clientes</RouterLink></header><form @submit.prevent="guardar" class="grid gap-4 sm:grid-cols-2"><label v-for="[key,label,type] in fields" :key="key" class="block"><span class="mb-1.5 block text-sm font-medium">{{label}}</span><input v-model="form[key]" :type="type" :min="key==='edad'?0:undefined" :max="key==='edad'?130:undefined" :required="!['contactoAlternativo','emailTrabajo'].includes(key)" class="w-full border border-zinc-300 px-3 py-2.5 outline-none focus:border-zinc-900"></label><label class="block sm:col-span-2"><span class="mb-1.5 block text-sm font-medium">Fotografia (JPG, PNG o WEBP, max. 7 MB)</span><input id="foto-cliente" type="file" accept="image/jpeg,image/png,image/webp" @change="onFile" class="block w-full text-sm file:mr-3 file:border-0 file:bg-zinc-100 file:px-3 file:py-2"></label><p v-if="mensaje" role="status" :class="error?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'" class="sm:col-span-2 px-3 py-2 text-sm">{{mensaje}}</p><div class="flex flex-wrap gap-3 sm:col-span-2"><button :disabled="cargando" class="bg-zinc-900 px-5 py-2.5 text-sm font-medium text-white disabled:opacity-50">{{cargando?'Guardando...':'Guardar cliente'}}</button><RouterLink to="/clientes" class="border border-zinc-300 px-5 py-2.5 text-sm">Lista de clientes</RouterLink></div></form></section></main></template>
